### ISSUE TITLE
Idea: bundle with `tsdx`

### ISSUE THREAD

**Issue by cilice** [ivx/react-skeletons#1]
https://github.com/jaredpalmer/tsdx

Jared Palmer's `tsdx` does exactly what you're trying to do and a bit more and it probably can save you a lot of maintenance effort. 

P.S. 💖

**Comment by tobilen** [comment]
i like it! will definitely check that out

**Comment by tobilen** [comment]
i've looked at it, looks nice. not much value in applying it retroactively though. will most likely use it for the next project
